version: '3'

services:
  db:
    restart: always
    image: mysql:5.7
    container_name: db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 1234@qwerA
      MYSQL_DATABASE: mysql_server
    ports:
      - 3306:3306
    volumes:
      - ./DB_DATA:/var/lib/mysql
  app:
    build: './'
    restart: always
    
volumes:
  DB_DATA:
